variables:
  - name: pythonVersion
    value: 3.12
    readonly: true

  - name: pythonArchitecture
    value: x64
    readonly: true

  - name: pythonSrcDirectory
    value: $(Build.Repository.LocalPath)/stratum/src/
    readonly: true

  - name: pythonProjectDirectory
    value: $(Build.Repository.LocalPath)/stratum/
    readonly: true

  - name: pythonPyprojectFilepath
    value: $(Build.Repository.LocalPath)/stratum/pyproject.toml
    readonly: true

  - name: pythonUnitTestsPaths
    value: $(Build.Repository.LocalPath)/stratum/tests/unit/
    readonly: true

  - name: PythonIntegrationtestsPaths
    value: $(Build.Repository.LocalPath)/stratum/tests/integration/
    readonly: true

  - name: PythonE2etestsPaths
    value: $(Build.Repository.LocalPath)/stratum/tests/e2e/
    readonly: true

  - name: devopsOrganisationName
    value: leevendaal
    readonly: true

  - name: artifactsFeedName
    value: leevendaal
    readonly: true

  - name: artifactsFeedView
    value: Release
    readonly: true
