variables:
- name: tenantName
  value: Team Rockstars IT

- name: tenantId
  value: 9e8cdb6a-eda5-4cca-8b83-b40f0074d999

- name: subscriptionName
  value: Visual Studio Enterprise Subscription – MPN

- name: subscriptionId
  value: e3aca0d2-d44e-4d75-b2a2-626da239e48c

- name: resourceRegion
  value: westeurope

- name: environment
  value: prod

- name: serviceConnection
  value: pers-reg-dev-eu-krijn

- name: deploymentEnvironment
  value: prod

- name: resourceGroupName
  value: rg-ccc-prod-01
