# Requirements:
# - Python version/architecture is set in pipeline

parameters:
  - name: pythonProjectDirectory
    type: string
    default: $(Build.Repository.LocalPath)

  - name: outputPath
    type: string
    default: $(Build.ArtifactStagingDirectory)/wheel/

steps:
  - script: |
      pip install build --quiet

      python -m build --version

      python -m build \
      --wheel ${{ parameters.pythonProjectDirectory }} \
      --outdir ${{ parameters.outputPath }}
    displayName: Build Python wheel
