# https://pycqa.github.io/isort/

# Requirements:
# - Python version/architecture is set in pipeline

parameters:
- name: enabled
  type: boolean
  default: true
  
- name: continueOnError
  type: boolean
  default: false

- name: targetPath
  type: string

- name: configFilepath
  type: string
  default: $(Build.Repository.LocalPath)/.tools/.isort.cfg

steps:
- script: |
    pip install isort --quiet

    isort --check-only ${{ parameters.targetPath }} \
    --settings-path ${{ parameters.configFilepath }} \
    --diff 
  displayName: Isort (formatter)
  condition: succeededOrFailed()
  continueOnError: ${{ parameters.continueOnError }}
  enabled: ${{ parameters.enabled }}
