# https://flake8.pycqa.org

# Requirements:
# - Python version/architecture is set in pipeline

parameters:
- name: enabled
  type: boolean
  default: true
  
- name: continueOnError
  type: boolean
  default: false

- name: targetPath
  type: string

- name: configFilepath
  type: string
  default: $(Build.Repository.LocalPath)/.tools/.flake8

steps:
- script: |
    pip install flake8 --quiet

    flake8 ${{ parameters.targetPath }} \
    --config ${{ parameters.configFilepath }}
  displayName: Flake8 (linter)
  condition: succeededOrFailed()
  continueOnError: ${{ parameters.continueOnError }}
  enabled: ${{ parameters.enabled }}
