# https://github.com/microsoft/pyright

# Note: Pyright has no option in CLI to specify which directory to check, it has to be set in te config.

# Requirements:
# - Python version/architecture is set in pipeline

parameters:
- name: enabled
  type: boolean
  default: true

- name: continueOnError
  type: boolean
  default: false
  
- name: targetPath
  type: string

- name: configFilepath
  type: string
  default: $(Build.Repository.LocalPath)/.tools/pyrightconfig.json

steps:
- script: |
    pip install pyright --quiet

    pyright ${{ parameters.targetPath }} --project ${{ parameters.configFilepath }} --level warning --warnings
  displayName: Pyright (type-checker)
  condition: succeededOrFailed()
  continueOnError: ${{ parameters.continueOnError }}
  enabled: ${{ parameters.enabled }}
