trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md

stages:
  - stage: Validate
    displayName: Validate code
    variables:
      - template: /.azure-pipelines/variables/environments/shared.yml
    jobs:
      - job: ValidateCode
        displayName: Validate code
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self
            fetchDepth: 0

          - task: UsepythonVersion@0
            displayName: Agent set Python ${{ variables.pythonVersion }} ${{ variables.pythonArchitecture }}
            inputs:
              versionSpec: ${{ variables.pythonVersion }}
              architecture: ${{ variables.pythonArchitecture }}

          - template: /.azure-pipelines/templates/install_poetry_requirements_v01.yml
            parameters:
              pythonPyprojectFilepath: ${{ variables.pythonPyprojectFilepath }}

          - template: /.azure-pipelines/templates/formatter_ruff_v01.yml
            parameters:
              targetPath: ${{ variables.pythonSrcDirectory }}
              continueOnError: true

          - template: /.azure-pipelines/templates/formatter_black_v01.yml
            parameters:
              targetPath: ${{ variables.pythonSrcDirectory }}
              continueOnError: true

          - template: /.azure-pipelines/templates/formatter_isort_v01.yml
            parameters:
              targetPath: ${{ variables.pythonSrcDirectory }}
              continueOnError: true

          - template: /.azure-pipelines/templates/linter_ruff_v01.yml
            parameters:
              targetPath: ${{ variables.pythonSrcDirectory }}
              continueOnError: true

          - template: /.azure-pipelines/templates/linter_pylint_v01.yml
            parameters:
              targetPath: ${{ variables.pythonSrcDirectory }}
              continueOnError: true

          - template: /.azure-pipelines/templates/linter_flake8_v01.yml
            parameters:
              targetPath: ${{ variables.pythonSrcDirectory }}
              continueOnError: true

          - template: /.azure-pipelines/templates/typechecker_mypy_v01.yml
            parameters:
              targetPath: ${{ variables.pythonSrcDirectory }}
              continueOnError: true
      
          - template: /.azure-pipelines/templates/typechecker_pyre_v01.yml
            parameters:
              targetPath: ${{ variables.pythonSrcDirectory }}
              continueOnError: true

          - template: /.azure-pipelines/templates/typechecker_pyright_v01.yml
            parameters:
              targetPath: ${{ variables.pythonSrcDirectory }}
              continueOnError: true

          - template: /.azure-pipelines/templates/scanner_gitleaks_v01.yml
            parameters:
              continueOnError: true

          - template: /.azure-pipelines/templates/scanner_trufflehog_v01.yml
            parameters:
              continueOnError: true

          - template: /.azure-pipelines/templates/scanner_bandit_v01.yml
            parameters:
              targetPath: ${{ variables.pythonSrcDirectory }}
              continueOnError: true

          - template: /.azure-pipelines/templates/scanner_semgrep_v01.yml
            parameters:
              targetPath: ${{ variables.pythonSrcDirectory }}
              continueOnError: true

          - template: /.azure-pipelines/templates/scanner_devskim_v01.yml
            parameters:
              targetPath: ${{ variables.pythonSrcDirectory }}
              continueOnError: true

          - template: /.azure-pipelines/templates/scanner_graudit_v01.yml
            parameters:
              targetPath: ${{ variables.pythonSrcDirectory }}
              continueOnError: true

          - template: /.azure-pipelines/templates/scanner_vulture_v01.yml
            parameters:
              targetPath: ${{ variables.pythonSrcDirectory }}
              continueOnError: true

          - publish: ${{ variables.pythonSrcDirectory }}
            displayName: Publish artifact module
            artifact: module

      - job: ValidateCodeDependencies
        displayName: Validate code dependencies
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self

          - task: UsepythonVersion@0
            displayName: Agent set Python ${{ variables.pythonVersion }} ${{ variables.pythonArchitecture }}
            inputs:
              versionSpec: ${{ variables.pythonVersion }}
              architecture: ${{ variables.pythonArchitecture }}

          - template: /.azure-pipelines/templates/scanner_ossaudit_v01.yml
            parameters:
              dependencyFilepath: ${{ variables.pythonPyprojectFilepath }}
              continueOnError: true

        # See notes in template. This template works but runs for 40 minutes once every 7 days to download database and cache it 7 days.
        # ossaudit provides nearly the same functionality without the 40 minute downloading delay.
        # - template: /.azure-pipelines/templates/scanner_owasp-dependency-check_v01.yml
        #   parameters:
        #     dependencyFilepath: ${{ variables.pythonPyprojectFilepath }}

      - job: UnitTestsGitDiff
        displayName: Unit Test (Relevant only)
        steps:
          - checkout: self
            fetchDepth: 0 # required for git diff

          - task: UsepythonVersion@0
            displayName: Agent set Python ${{ variables.pythonVersion }} ${{ variables.pythonArchitecture }}
            inputs:
              versionSpec: ${{ variables.pythonVersion }}
              architecture: ${{ variables.pythonArchitecture }}

          - template: /.azure-pipelines/templates/install_pip_editable_v01.yml
            parameters:
              pythonProjectDirectory: ${{ variables.pythonProjectDirectory }}

          - template: /.azure-pipelines/templates/test_pytest-diff_v01.yml
            parameters:
              pythonProjectDirectory: ${{ variables.pythonProjectDirectory }}
              testsPaths: ${{ variables.pythonUnitTestsPaths }}

          - template: /.azure-pipelines/templates/test_pytest_v01.yml
            parameters:
              testsPaths: $(testFiles)
              coveragePath: ${{ variables.pythonSrcDirectory }}

  - stage: UnitTest
    displayName: Unit test
    dependsOn: Validate
    variables:
      - template: /.azure-pipelines/variables/environments/shared.yml
    jobs:
      - job: UnitTestAll
        displayName: Unit Test (All)
        steps:
          - checkout: self

          - task: UsepythonVersion@0
            displayName: Agent set Python ${{ variables.pythonVersion }} ${{ variables.pythonArchitecture }}
            inputs:
              versionSpec: ${{ variables.pythonVersion }}
              architecture: ${{ variables.pythonArchitecture }}

          - template: /.azure-pipelines/templates/install_pip_editable_v01.yml
            parameters:
              pythonProjectDirectory: ${{ variables.pythonProjectDirectory }}

          - template: /.azure-pipelines/templates/test_pytest_v01.yml
            parameters:
              testsPaths: ${{ variables.pythonUnitTestsPaths }}
              coveragePath: ${{ variables.pythonSrcDirectory }}
      
      - template: /.azure-pipelines/templates/test_pytest-split_v01.yml
        parameters:
          pythonVersion: ${{ variables.pythonVersion }}
          pythonArchitecture: ${{ variables.pythonArchitecture }}
          pythonProjectDirectory: ${{ variables.pythonProjectDirectory }}
          testsPaths: ${{ variables.pythonUnitTestsPaths }}
          coveragePath: ${{ variables.pythonSrcDirectory }}

  - stage: Build
    displayName: Build
    dependsOn: 
      - UnitTest
      - E2eTest
    variables:
      - template: /.azure-pipelines/variables/environments/shared.yml
    jobs:
      - job: buildWheel
        displayName: Build wheel
        steps:
          - checkout: self

          - task: UsepythonVersion@0
            displayName: python ${{ variables.pythonVersion }} ${{ variables.pythonArchitecture }}
            inputs:
              versionSpec: ${{ variables.pythonVersion }}
              architecture: ${{ variables.pythonArchitecture }}

          - template: /.azure-pipelines/templates/build_wheel_bdist_v01.yml
            parameters:
              pythonProjectDirectory: ${{ variables.pythonProjectDirectory }}

          - template: /.azure-pipelines/templates/extract_pyproject_metadata_v01.yml
            parameters:
              pyprojectFilepath: $(Build.SourcesDirectory)/pyproject.toml

          - publish: $(Build.ArtifactStagingDirectory)/wheel/
            displayName: Publish artifact wheel
            artifact: wheel

  - stage: Profile
    displayName: Profile
    dependsOn: Build
    variables:
      - template: /.azure-pipelines/variables/environments/shared.yml
    jobs:
      - job: cProfile
        displayName: cProfile (deterministic profiler)
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self

          - task: UsepythonVersion@0
            displayName: python ${{ variables.pythonVersion }} ${{ variables.pythonArchitecture }}
            inputs:
              versionSpec: ${{ variables.pythonVersion }}
              architecture: ${{ variables.pythonArchitecture }}

          # TODO not finished yet.
          # - template: /.azure-pipelines/templates/profiler_cprofile_v01.yml
          #   parameters:
          #     targetPath: ${{ variables.pythonSrcDirectory }}

  - stage: DeployLocal
    displayName: Deploy to @local view
    dependsOn: Profile
    variables:
      - template: /.azure-pipelines/variables/environments/shared.yml
      - template: /.azure-pipelines/variables/environments/dev.yml
    jobs:
      - deployment: Deploy
        displayName: Deploy to ${{ variables.artifactsFeedName }}@Local
        environment: ${{ variables.deploymentEnvironment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /.azure-pipelines/templates/deploy_artifacts_python_wheel_v01.yml
                  parameters:
                    deploymentEnvironment: ${{ variables.deploymentEnvironment}}
                    artifactsFeedName: ${{ variables.artifactsFeedName}}
      - deployment: Promote
        dependsOn: Deploy
        displayName: Promote to ${{ variables.artifactsFeedName }}@${{ variables.artifactsFeedView }}
        environment: ${{ variables.deploymentEnvironment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /.azure-pipelines/templates/promote_artifacts_package_v01.yml
                  parameters:
                    deploymentEnvironment: ${{ variables.deploymentEnvironment }}
                    pythonVersion: ${{ variables.pythonVersion }}
                    pythonArchitecture: ${{ variables.pythonArchitecture }}
                    devopsOrganisationName: ${{ variables.devopsOrganisationName}}
                    devopsAccessToken: $(System.AccessToken)
                    artifactsFeedName: ${{ variables.artifactsFeedName }}
                    artifactsFeedView: ${{ variables.artifactsFeedView }}
                    packageName: $[ stageDependencies.build.buildWheel.outputs['pyprojectMetadata.packageName'] ]
                    packageVersion: $[ stageDependencies.build.buildWheel.outputs['pyprojectMetadata.packageVersion'] ]

    # - template: /.azure-pipelines/templates/jobs/wheel_deploy.yml
    #   parameters:
    #     pythonVersion: ${{ variables.pythonVersion }}
    #     pythonArchitecture: ${{ variables.pythonArchitecture }}
    #     artifactFeedName: ${{ variables.artifactFeedName }}

  # - stage: Promote
  #   displayName: Promote to pre-release view
  #   dependsOn:
  #   - DeployLocal
  #   variables:
  # - template: /.azure-pipelines/variables/environments/shared.yml
  # - template: /.azure-pipelines/variables/environments/prod.yml
  #   jobs:
  #   - template: /.azure-pipelines/templates/jobs/package_promote.yml
  #     parameters:
  #       deployEnvironment: ${{ variables.deployEnvironment }}
  #       pythonVersion: ${{ variables.pythonVersion }}
  #       pythonArchitecture: ${{ variables.pythonArchitecture }}
  #       artifactFeedName: ${{ variables.artifactFeedName }}
  #       artifactFeedView: ${{ variables.artifactFeedView }}
  #       artifactFeedId: ${{ variables.artifactFeedId }}
  #       packageName: $(packageName)
  #       packageVersion: $(packageVersion)
