version: '3'

services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.12.4
      target: base
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
