services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: base:ubuntu-24.04
    volumes:
      - ../../:/workspace:cached
    command: sleep infinity
